services:
  server:
    build:
      context: ../..
      args:
        APACHE_CONF: ${APACHE_CONF}
        APP_ENV: ${APP_ENV}
    ports:
      - ${PORT}:80
    depends_on:
      - db
    volumes:
      - .env:/var/www/html/.env
    container_name: videgrenier-web-prod

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ../../sql/prod_import.sql:/docker-entrypoint-initdb.d/import.sql
    ports:
      - 3308:3306
    container_name: videgrenier-db-prod

volumes:
  db-data: