services:
  server:
    build:
      context: ../..
      args:
        APACHE_CONF: ${APACHE_CONF}
        APP_ENV: ${APP_ENV}
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:80
    depends_on:
      - db
    container_name: videgrenier-web-${APP_ENV}

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ${SQL_FILE}:/docker-entrypoint-initdb.d/import.sql
    ports:
      - ${DB_PORT}:${DB_PORT}
    container_name: videgrenier-db-${APP_ENV}

volumes:
  db-data: